### PR TITLE
update data and readme for better clarity on update process

### PR DESCRIPTION
**Pull request by johnwesely**
#Details
This PR updates the data with the most recent 2023 numbers, and also overhauls the read me file to make updating data easier going forwards.

#Steps to Test
1. open repo in VS Code. 
2. Download the "Live Server" extension
3. open the index.html file and click the Go Live button on the blue bar at the bottom of VS Code.
4. Ensure line extends past 2020, the last year in the previous version and that the inflation checkbox works without causing the graph to go haywire.
5. Look at new readme file and ensure instructions for further updates are legible and correct.

#Linked tasks
[#863gtw4g4](https://app.clickup.com/t/863gtw4g4)

### CODE REVIEW

**Comment by johnwesely** [comment]
@cpastre1 I do not have the proper permissions to update Netlify, so that this will build properly. It should be fairly straightforward for you to do it, but please let me know if you have any questions.

**Review by cpastre1 — APPROVED** [review]
Looks great! Thanks @johnwesely.

**Comment by cpastre1** [comment]
@johnwesely Sorry, I just noticed an issue at [taxfoundation.org/cigarette-tax-revenue-tool ](https://taxfoundation.org/cigarette-tax-revenue-tool)that I didn't when previewing the tool via VS code: It appears data is missing for the "United States" dropdown (see below). When you toggle from any other option to "United States" the data does not update, either. Can you please help troubleshoot? 
image

**Comment by johnwesely** [comment]
Colby,

I am seeing this as well and looking into it currently.

- John Wesely

**Comment by johnwesely** [comment]
Colby,

I was able to push a fix for this. It may take a few minutes to go live on
the TF website. I will also push an update to the readme with instructions
for how this can be avoided next time.

- John Wesely

**Comment by cpastre1** [comment]
Thank you @johnwesely! The fix already seems to have taken. Appreciate the quick turnaround.

**Pull request merged**
